name: Version, build, publish

on:
  push:
    branches:
      - main

jobs:

  semantic_release_next_version:
    name: Next version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16
      - run: npm install
      - run: npx semantic-release --dry-run
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: semantic-release
          path: |
            gtdb_itol_decorate/__init__.py
            CHANGELOG.md
          retention-days: 1
    outputs:
      version: ${{ steps.semantic_release.outputs.version }}

  build_python:
    name: Python build
    runs-on: ubuntu-latest
    needs: semantic_release_next_version
    if: needs.semantic_release_next_version.outputs.version != ''
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: semantic-release
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: |
          python -m pip install -U setuptools wheel
          python setup.py sdist bdist_wheel
      - uses: actions/upload-artifact@v3
        with:
          name: pypi
          path: dist/*
          retention-days: 1

  test_python_sdist:
    name: Python test *.tar.gz
    runs-on: ubuntu-latest
    needs: build_python
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: pypi
          path: dist
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: python -m pip install dist/*.tar.gz

  test_python_wheel:
    name: Python test *.whl
    runs-on: ubuntu-latest
    needs: build_python
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: pypi
          path: dist
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: python -m pip install dist/*.whl

  semantic_release_publish:
    name: Publish to GitHub
    needs: [test_python_sdist, test_python_wheel]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16
      - run: npm install
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload_pypi:
    name: Publish to PyPI
    needs: [semantic_release_publish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: pypi
          path: dist
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: |
          python -m pip install -U twine
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
